### PR TITLE
Split maint

### PR DESCRIPTION
**Pull request by gonuke**
Modularizes maintenance tasks - I haven't tested it because I'm not sure how to do so without possibly pushing things to upload location

### CODE REVIEW

**Comment by gonuke** [comment]
Also fixed spelling of filename

**Comment by gidden** [comment]
Thanks @gonuke, I think this is almost there. The main question I have is what the "default" behavior should be (or if it should be allowed). Right now, if I run `$ ./maintenance.sh -v 1.3.0`, I get a no op. I think either an error should be raised or it should default to the full update.

Separately, would you mind updating cyclus/cyclus.github.com#133 as well with the correct usage?

**Comment by gonuke** [comment]
I've chosen safety over convenience and issued an error for the no-op.

**Comment by gidden** [comment]
Ok, lookin' better. It's still not clear from the usage that you can do
./maintenence.sh -v XXX -r (untill you read past everything else). Can you
add another line to the usage that is something like `./maintenance.sh
-v|--version <version_string> [-r|--release]`?

On Fri, May 8, 2015 at 11:04 AM, Paul Wilson notifications@github.com
wrote:

> I've chosen safety over convenience and issued an error for the no-op.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gidden/ciclus/pull/3#issuecomment-100281537.

## 

Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
merged, thank you very much @gonuke

**Pull request merged**
