### PR TITLE
Swc

### PR DESCRIPTION
**Pull request by gonuke**
Finally found something that I think I know how to do without taking an hour to ramp up my skillz....

Not sure how to test this, though?

### CODE REVIEW

**Comment by gidden** [comment]
Thanks @gonuke, I'll give this a spin when I get in the office

**Comment by gidden** [comment]
Just checking basics, I see the following error:

```
$ ./make_release_notes.sh 
./make_release_notes.sh: line 36: syntax error near unexpected token `exit'
```

**Comment by gonuke** [comment]
Sorry - that was totally lame of me.... I can test it better - other than the binstar upload part!  I'll do more testing and ping you...

**Comment by gidden** [comment]
The `make_release_notes.sh` script is benign and can help you test the input/usage stuff. It only creates a file (the notes).

**Comment by gonuke** [comment]
I think I've done as much testing as I can without starting to push/upload things to the wild.

**Comment by gidden** [comment]
looks good, thanks @gonuke

**Pull request merged**
